version: '3'

tasks:
  gen-server:
    cmds:
    - buf generate --template buf.gen.server.yaml ./proto/greeter.proto
  gen-client:
    cmds:
    - buf generate --template buf.gen.client.yaml ./proto/greeter.proto