version: '3'

tasks:
  install-deps:
    cmds:
      - brew install protobuf
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - export PATH="$PATH:$(go env GOPATH)/bin"
  gen-server:
    cmds:
      - |
        protoc --go_out=./server/pkg/greeter --go_opt=paths=source_relative \
        --go-grpc_out=./server/pkg/greeter --go-grpc_opt=paths=source_relative \
        proto/greeter.proto