// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: greeter.proto

package greeterconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	greeter "greeter/pkg/greeter"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ToDoServiceName is the fully-qualified name of the ToDoService service.
	ToDoServiceName = "greeter.v1.ToDoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ToDoServiceCreateProcedure is the fully-qualified name of the ToDoService's Create RPC.
	ToDoServiceCreateProcedure = "/greeter.v1.ToDoService/Create"
	// ToDoServiceUpdateProcedure is the fully-qualified name of the ToDoService's Update RPC.
	ToDoServiceUpdateProcedure = "/greeter.v1.ToDoService/Update"
	// ToDoServiceDeleteProcedure is the fully-qualified name of the ToDoService's Delete RPC.
	ToDoServiceDeleteProcedure = "/greeter.v1.ToDoService/Delete"
	// ToDoServiceGetOneProcedure is the fully-qualified name of the ToDoService's GetOne RPC.
	ToDoServiceGetOneProcedure = "/greeter.v1.ToDoService/GetOne"
	// ToDoServiceGetAllProcedure is the fully-qualified name of the ToDoService's GetAll RPC.
	ToDoServiceGetAllProcedure = "/greeter.v1.ToDoService/GetAll"
	// ToDoServiceUpdateStatusProcedure is the fully-qualified name of the ToDoService's UpdateStatus
	// RPC.
	ToDoServiceUpdateStatusProcedure = "/greeter.v1.ToDoService/UpdateStatus"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	toDoServiceServiceDescriptor            = greeter.File_greeter_proto.Services().ByName("ToDoService")
	toDoServiceCreateMethodDescriptor       = toDoServiceServiceDescriptor.Methods().ByName("Create")
	toDoServiceUpdateMethodDescriptor       = toDoServiceServiceDescriptor.Methods().ByName("Update")
	toDoServiceDeleteMethodDescriptor       = toDoServiceServiceDescriptor.Methods().ByName("Delete")
	toDoServiceGetOneMethodDescriptor       = toDoServiceServiceDescriptor.Methods().ByName("GetOne")
	toDoServiceGetAllMethodDescriptor       = toDoServiceServiceDescriptor.Methods().ByName("GetAll")
	toDoServiceUpdateStatusMethodDescriptor = toDoServiceServiceDescriptor.Methods().ByName("UpdateStatus")
)

// ToDoServiceClient is a client for the greeter.v1.ToDoService service.
type ToDoServiceClient interface {
	Create(context.Context, *connect.Request[greeter.CreateRequest]) (*connect.Response[greeter.CreateResponse], error)
	Update(context.Context, *connect.Request[greeter.UpdateRequest]) (*connect.Response[greeter.UpdateResponse], error)
	Delete(context.Context, *connect.Request[greeter.DeleteRequest]) (*connect.Response[emptypb.Empty], error)
	GetOne(context.Context, *connect.Request[greeter.GetOneRequest]) (*connect.Response[greeter.GetOneResponse], error)
	GetAll(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[greeter.GetAllResponse], error)
	UpdateStatus(context.Context, *connect.Request[greeter.UpdateStatusRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewToDoServiceClient constructs a client for the greeter.v1.ToDoService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewToDoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ToDoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &toDoServiceClient{
		create: connect.NewClient[greeter.CreateRequest, greeter.CreateResponse](
			httpClient,
			baseURL+ToDoServiceCreateProcedure,
			connect.WithSchema(toDoServiceCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[greeter.UpdateRequest, greeter.UpdateResponse](
			httpClient,
			baseURL+ToDoServiceUpdateProcedure,
			connect.WithSchema(toDoServiceUpdateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[greeter.DeleteRequest, emptypb.Empty](
			httpClient,
			baseURL+ToDoServiceDeleteProcedure,
			connect.WithSchema(toDoServiceDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getOne: connect.NewClient[greeter.GetOneRequest, greeter.GetOneResponse](
			httpClient,
			baseURL+ToDoServiceGetOneProcedure,
			connect.WithSchema(toDoServiceGetOneMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAll: connect.NewClient[emptypb.Empty, greeter.GetAllResponse](
			httpClient,
			baseURL+ToDoServiceGetAllProcedure,
			connect.WithSchema(toDoServiceGetAllMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateStatus: connect.NewClient[greeter.UpdateStatusRequest, emptypb.Empty](
			httpClient,
			baseURL+ToDoServiceUpdateStatusProcedure,
			connect.WithSchema(toDoServiceUpdateStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// toDoServiceClient implements ToDoServiceClient.
type toDoServiceClient struct {
	create       *connect.Client[greeter.CreateRequest, greeter.CreateResponse]
	update       *connect.Client[greeter.UpdateRequest, greeter.UpdateResponse]
	delete       *connect.Client[greeter.DeleteRequest, emptypb.Empty]
	getOne       *connect.Client[greeter.GetOneRequest, greeter.GetOneResponse]
	getAll       *connect.Client[emptypb.Empty, greeter.GetAllResponse]
	updateStatus *connect.Client[greeter.UpdateStatusRequest, emptypb.Empty]
}

// Create calls greeter.v1.ToDoService.Create.
func (c *toDoServiceClient) Create(ctx context.Context, req *connect.Request[greeter.CreateRequest]) (*connect.Response[greeter.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls greeter.v1.ToDoService.Update.
func (c *toDoServiceClient) Update(ctx context.Context, req *connect.Request[greeter.UpdateRequest]) (*connect.Response[greeter.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls greeter.v1.ToDoService.Delete.
func (c *toDoServiceClient) Delete(ctx context.Context, req *connect.Request[greeter.DeleteRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// GetOne calls greeter.v1.ToDoService.GetOne.
func (c *toDoServiceClient) GetOne(ctx context.Context, req *connect.Request[greeter.GetOneRequest]) (*connect.Response[greeter.GetOneResponse], error) {
	return c.getOne.CallUnary(ctx, req)
}

// GetAll calls greeter.v1.ToDoService.GetAll.
func (c *toDoServiceClient) GetAll(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[greeter.GetAllResponse], error) {
	return c.getAll.CallUnary(ctx, req)
}

// UpdateStatus calls greeter.v1.ToDoService.UpdateStatus.
func (c *toDoServiceClient) UpdateStatus(ctx context.Context, req *connect.Request[greeter.UpdateStatusRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.updateStatus.CallUnary(ctx, req)
}

// ToDoServiceHandler is an implementation of the greeter.v1.ToDoService service.
type ToDoServiceHandler interface {
	Create(context.Context, *connect.Request[greeter.CreateRequest]) (*connect.Response[greeter.CreateResponse], error)
	Update(context.Context, *connect.Request[greeter.UpdateRequest]) (*connect.Response[greeter.UpdateResponse], error)
	Delete(context.Context, *connect.Request[greeter.DeleteRequest]) (*connect.Response[emptypb.Empty], error)
	GetOne(context.Context, *connect.Request[greeter.GetOneRequest]) (*connect.Response[greeter.GetOneResponse], error)
	GetAll(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[greeter.GetAllResponse], error)
	UpdateStatus(context.Context, *connect.Request[greeter.UpdateStatusRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewToDoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewToDoServiceHandler(svc ToDoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	toDoServiceCreateHandler := connect.NewUnaryHandler(
		ToDoServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(toDoServiceCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toDoServiceUpdateHandler := connect.NewUnaryHandler(
		ToDoServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(toDoServiceUpdateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toDoServiceDeleteHandler := connect.NewUnaryHandler(
		ToDoServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(toDoServiceDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toDoServiceGetOneHandler := connect.NewUnaryHandler(
		ToDoServiceGetOneProcedure,
		svc.GetOne,
		connect.WithSchema(toDoServiceGetOneMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toDoServiceGetAllHandler := connect.NewUnaryHandler(
		ToDoServiceGetAllProcedure,
		svc.GetAll,
		connect.WithSchema(toDoServiceGetAllMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toDoServiceUpdateStatusHandler := connect.NewUnaryHandler(
		ToDoServiceUpdateStatusProcedure,
		svc.UpdateStatus,
		connect.WithSchema(toDoServiceUpdateStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/greeter.v1.ToDoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ToDoServiceCreateProcedure:
			toDoServiceCreateHandler.ServeHTTP(w, r)
		case ToDoServiceUpdateProcedure:
			toDoServiceUpdateHandler.ServeHTTP(w, r)
		case ToDoServiceDeleteProcedure:
			toDoServiceDeleteHandler.ServeHTTP(w, r)
		case ToDoServiceGetOneProcedure:
			toDoServiceGetOneHandler.ServeHTTP(w, r)
		case ToDoServiceGetAllProcedure:
			toDoServiceGetAllHandler.ServeHTTP(w, r)
		case ToDoServiceUpdateStatusProcedure:
			toDoServiceUpdateStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedToDoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedToDoServiceHandler struct{}

func (UnimplementedToDoServiceHandler) Create(context.Context, *connect.Request[greeter.CreateRequest]) (*connect.Response[greeter.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("greeter.v1.ToDoService.Create is not implemented"))
}

func (UnimplementedToDoServiceHandler) Update(context.Context, *connect.Request[greeter.UpdateRequest]) (*connect.Response[greeter.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("greeter.v1.ToDoService.Update is not implemented"))
}

func (UnimplementedToDoServiceHandler) Delete(context.Context, *connect.Request[greeter.DeleteRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("greeter.v1.ToDoService.Delete is not implemented"))
}

func (UnimplementedToDoServiceHandler) GetOne(context.Context, *connect.Request[greeter.GetOneRequest]) (*connect.Response[greeter.GetOneResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("greeter.v1.ToDoService.GetOne is not implemented"))
}

func (UnimplementedToDoServiceHandler) GetAll(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[greeter.GetAllResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("greeter.v1.ToDoService.GetAll is not implemented"))
}

func (UnimplementedToDoServiceHandler) UpdateStatus(context.Context, *connect.Request[greeter.UpdateStatusRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("greeter.v1.ToDoService.UpdateStatus is not implemented"))
}
