// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: greeter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_PENDING            Status = 1
	Status_COMPLETED          Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "COMPLETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"COMPLETED":          2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_greeter_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_greeter_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{0}
}

type ToDoDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=greeter.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToDoDetails) Reset() {
	*x = ToDoDetails{}
	mi := &file_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToDoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoDetails) ProtoMessage() {}

func (x *ToDoDetails) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoDetails.ProtoReflect.Descriptor instead.
func (*ToDoDetails) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *ToDoDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToDoDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToDoDetails) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type ToDoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Item          *ToDoDetails           `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToDoItem) Reset() {
	*x = ToDoItem{}
	mi := &file_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToDoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoItem) ProtoMessage() {}

func (x *ToDoItem) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoItem.ProtoReflect.Descriptor instead.
func (*ToDoItem) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *ToDoItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToDoItem) GetItem() *ToDoDetails {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ToDoItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ToDoDetails           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetItem() *ToDoDetails {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ToDoItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetItem() *ToDoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ToDoDetails           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetItem() *ToDoDetails {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ToDoItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResponse) GetItem() *ToDoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *GetOneRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ToDoItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneResponse) Reset() {
	*x = GetOneResponse{}
	mi := &file_greeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneResponse) ProtoMessage() {}

func (x *GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneResponse.ProtoReflect.Descriptor instead.
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{8}
}

func (x *GetOneResponse) GetItem() *ToDoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ToDoItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_greeter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllResponse) GetItems() []*ToDoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_greeter_proto protoreflect.FileDescriptor

const file_greeter_proto_rawDesc = "" +
	"\n" +
	"\rgreeter.proto\x12\n" +
	"greeter.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"q\n" +
	"\vToDoDetails\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.greeter.v1.StatusR\x06status\"\x82\x01\n" +
	"\bToDoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x04item\x18\x02 \x01(\v2\x17.greeter.v1.ToDoDetailsR\x04item\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"<\n" +
	"\rCreateRequest\x12+\n" +
	"\x04item\x18\x01 \x01(\v2\x17.greeter.v1.ToDoDetailsR\x04item\":\n" +
	"\x0eCreateResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.greeter.v1.ToDoItemR\x04item\"<\n" +
	"\rUpdateRequest\x12+\n" +
	"\x04item\x18\x01 \x01(\v2\x17.greeter.v1.ToDoDetailsR\x04item\":\n" +
	"\x0eUpdateResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.greeter.v1.ToDoItemR\x04item\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1f\n" +
	"\rGetOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x0eGetOneResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.greeter.v1.ToDoItemR\x04item\"<\n" +
	"\x0eGetAllResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.greeter.v1.ToDoItemR\x05items*<\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x022\xcb\x02\n" +
	"\vToDoService\x12?\n" +
	"\x06Create\x12\x19.greeter.v1.CreateRequest\x1a\x1a.greeter.v1.CreateResponse\x12?\n" +
	"\x06Update\x12\x19.greeter.v1.UpdateRequest\x1a\x1a.greeter.v1.UpdateResponse\x12;\n" +
	"\x06Delete\x12\x19.greeter.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x06GetOne\x12\x19.greeter.v1.GetOneRequest\x1a\x1a.greeter.v1.GetOneResponse\x12<\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x1a.greeter.v1.GetAllResponseB\x89\x01\n" +
	"\x0ecom.greeter.v1B\fGreeterProtoP\x01Z greeter/server/pkg/greeter/proto\xa2\x02\x03GXX\xaa\x02\n" +
	"Greeter.V1\xca\x02\n" +
	"Greeter\\V1\xe2\x02\x16Greeter\\V1\\GPBMetadata\xea\x02\vGreeter::V1b\x06proto3"

var (
	file_greeter_proto_rawDescOnce sync.Once
	file_greeter_proto_rawDescData []byte
)

func file_greeter_proto_rawDescGZIP() []byte {
	file_greeter_proto_rawDescOnce.Do(func() {
		file_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greeter_proto_rawDesc), len(file_greeter_proto_rawDesc)))
	})
	return file_greeter_proto_rawDescData
}

var file_greeter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_greeter_proto_goTypes = []any{
	(Status)(0),                   // 0: greeter.v1.Status
	(*ToDoDetails)(nil),           // 1: greeter.v1.ToDoDetails
	(*ToDoItem)(nil),              // 2: greeter.v1.ToDoItem
	(*CreateRequest)(nil),         // 3: greeter.v1.CreateRequest
	(*CreateResponse)(nil),        // 4: greeter.v1.CreateResponse
	(*UpdateRequest)(nil),         // 5: greeter.v1.UpdateRequest
	(*UpdateResponse)(nil),        // 6: greeter.v1.UpdateResponse
	(*DeleteRequest)(nil),         // 7: greeter.v1.DeleteRequest
	(*GetOneRequest)(nil),         // 8: greeter.v1.GetOneRequest
	(*GetOneResponse)(nil),        // 9: greeter.v1.GetOneResponse
	(*GetAllResponse)(nil),        // 10: greeter.v1.GetAllResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_greeter_proto_depIdxs = []int32{
	0,  // 0: greeter.v1.ToDoDetails.status:type_name -> greeter.v1.Status
	1,  // 1: greeter.v1.ToDoItem.item:type_name -> greeter.v1.ToDoDetails
	11, // 2: greeter.v1.ToDoItem.created_at:type_name -> google.protobuf.Timestamp
	1,  // 3: greeter.v1.CreateRequest.item:type_name -> greeter.v1.ToDoDetails
	2,  // 4: greeter.v1.CreateResponse.item:type_name -> greeter.v1.ToDoItem
	1,  // 5: greeter.v1.UpdateRequest.item:type_name -> greeter.v1.ToDoDetails
	2,  // 6: greeter.v1.UpdateResponse.item:type_name -> greeter.v1.ToDoItem
	2,  // 7: greeter.v1.GetOneResponse.item:type_name -> greeter.v1.ToDoItem
	2,  // 8: greeter.v1.GetAllResponse.items:type_name -> greeter.v1.ToDoItem
	3,  // 9: greeter.v1.ToDoService.Create:input_type -> greeter.v1.CreateRequest
	5,  // 10: greeter.v1.ToDoService.Update:input_type -> greeter.v1.UpdateRequest
	7,  // 11: greeter.v1.ToDoService.Delete:input_type -> greeter.v1.DeleteRequest
	8,  // 12: greeter.v1.ToDoService.GetOne:input_type -> greeter.v1.GetOneRequest
	12, // 13: greeter.v1.ToDoService.GetAll:input_type -> google.protobuf.Empty
	4,  // 14: greeter.v1.ToDoService.Create:output_type -> greeter.v1.CreateResponse
	6,  // 15: greeter.v1.ToDoService.Update:output_type -> greeter.v1.UpdateResponse
	12, // 16: greeter.v1.ToDoService.Delete:output_type -> google.protobuf.Empty
	9,  // 17: greeter.v1.ToDoService.GetOne:output_type -> greeter.v1.GetOneResponse
	10, // 18: greeter.v1.ToDoService.GetAll:output_type -> greeter.v1.GetAllResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_greeter_proto_init() }
func file_greeter_proto_init() {
	if File_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greeter_proto_rawDesc), len(file_greeter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_proto_goTypes,
		DependencyIndexes: file_greeter_proto_depIdxs,
		EnumInfos:         file_greeter_proto_enumTypes,
		MessageInfos:      file_greeter_proto_msgTypes,
	}.Build()
	File_greeter_proto = out.File
	file_greeter_proto_goTypes = nil
	file_greeter_proto_depIdxs = nil
}
